### ISSUE TITLE
`0.7.0` is not available on crates.io

### ISSUE THREAD

**Issue by imrn99** [elrnv/vtkio#42]
Hello all,

I am currently working on a project aiming to implement a specific data structures for meshing application (see https://github.com/LIHPC-Computational-Geometry/honeycomb). I found great success using `vtkio` for handling input/output so far, however I had to use version `0.6.3` in order to be able to publish our crates (because of cargo requirements). This creates a number of issues with outdated dependencies containing code that will be rejected in future Rust versions. 

Would it be possible to publish `0.7.0`, or an alpha version of it, on  crates.io? From what I can tell, the code of the `master` branch fixes those dependency issues (and works for my use case, which does not require the `xml` feature). If I can help in any way, please let me know.

PS: Thank you for your work on this crate, having a clean VTK parser implemented in Rust spared me a lot of headaches :)

**Comment by elrnv** [comment]
Thank you for the issue! I am just now catching up on the backlog of issues. Good idea about publishing an alpha release. I will likely get to it this week.

**Comment by elrnv** [comment]
I updated all the dependencies and added an rc1 version to crates.io here: https://crates.io/crates/vtkio/0.7.0-rc1

Hope this helps!

**Comment by imrn99** [comment]
Thank you for your work!

**Comment by philbucher** [comment]
Hi,
Are there any plans for a proper release of version 0.7? It is still a release candidate on crates.io, it would be easier to use if it was a regular release
Thanks!
