### ISSUE TITLE
Recognize format "ASCII"

### ISSUE THREAD

**Issue by KonradKaralus** [elrnv/vtkio#52]
Reading a file that uses ``format="ASCII"`` currently results in the error 
```XML(Deserialization(Custom("unknown variant `ASCII`, expected one of `appended`, `binary`, `ascii`")))```.

Given the fact that the vtk specification only uses ``format="ascii"``, this technically is correct but also accepting files with ``format="ASCII"`` would be a minor change, which would make the crate more flexible. Paraview also accepts these files.

**Comment by elrnv** [comment]
Nice catch, thank you for the issue!

**Comment by elrnv** [comment]
Fixed by #53
