### ISSUE TITLE
Non-linear cell types

### ISSUE THREAD

**Issue by Andlon** [elrnv/vtkio#7]
I have a somewhat urgent need for support for non-linear cells. That is, for the legacy format, the `VTK_QUADRATIC_*` cell types. Since we're up against a deadline, I'd probably hack something together in a local fork before wrapping it up for contribution after the deadline (February at best).

Before I dive into the code base of `vtkio`, however, I wanted to ask if there's a specific reason that these cell types are not currently supported, or is it simply an omission? Do they need to be treated differently? Any advice you might have would be greatly appreciated!

**Comment by elrnv** [comment]
It is simply an omission. I think it should be straight forward to add those to the `CellType` enum. The most important part is testing. I think taking the example from the PDF linked is sufficient, but if you have an interesting but small example that would be a great addition.

**Comment by elrnv** [comment]
I added a quick PR ( #8 ) with the change, and it seems to work for a simple test case. But additional tests are welcome. If you are interested in going through the motions of submitting a PR yourself that's also fine by me. I am not sure how to add you as a reviewer to that PR though.

**Comment by Andlon** [comment]
Sweet! Thanks a lot. I just tried it out with some quadratic quads in VTK, and it works splendidly. As I said in #8, I'll try to write up some more exhaustive tests some time during the week, if I can squeeze the time in.

**Comment by elrnv** [comment]
More tests would be great! Thank you for this issue :)

**Comment by Andlon** [comment]
So I haven't forgotten about contributing the tests, but I'm having a hard time finding time for it right now. I should have more time in February, so I hope I will be able to pick up the thread again then (and possibly start work on the XML formats as discussed in #4).

**Comment by elrnv** [comment]
No worries, I assume siggraph deadline? Thanks for the update. BTW I have a potentially useful crate called [gut](https://gitlab.com/elrnv/gut) that i use to work with tet meshes, triangle meshes and polygon meshes. It’s not well documented but it has some useful utilities for storing and getting  mesh attributes. For example, this code loads a vtk polygon mesh, triangulated it and gets a vertex velocity attribute:

```rust
use gut::{mesh::{TriMesh, Attrib, topology::*}, io::load_polymesh};
let mesh = TriMesh::from(load_polymesh(“mesh.vtk”).unwrap());
let vel = mesh.attrib_as_slice::<[f64; 3], VertexIndex>(”vel”);
```

Hope that helps, cheers and good luck!

**Comment by Andlon** [comment]
Yeah, that's right. Pretty busy now as I want to have a minimal prototype of all the major parts before the holiday break so that we can start setting up the more involved scenes. It's gonna be a tight race, I guess.

That looks like a really useful crate! I might use it for the tet mesh surface extraction for some basic synthetic examples, perhaps. And I'm curious about the mesh merging/splitting stuff.

After we get accepted for publication somewhere (whether SIGGRAPH or somewhere else), I'll have quite a lot of stuff that I want to publish as crates. I'm very grateful for `vtkio` - perhaps there's something in our work that you may find of use as well. It would be neat to build more of a capable ecosystem for physics-based animation in Rust, and I'd love to collaborate on that. Are you submitting anything for SIGGRAPH this time?

In any case, thanks a lot!

**Comment by elrnv** [comment]
Yes we are working on something, and I also want to release the code for reproducibility. I am very interested in collaborating on a better ecosystem.

I have been looking for a solid linear algebra library with lazy linear algebra (like in Eigen) block matrix and sparse matrix capabilities and reasonable performance, but couldn't find anything in Rust (or anywhere else for that matter). A somewhat complete solution for this would include something like sprs, ndarray and nalgebra, but it is not possible to compose these AFAICT. For example, creating a sparse block matrix and then be able to multiply it by a sparse or dense vector or block vector would be nice. I have somewhat of a solution for this I use in my own code, but it has a few warts and definitely needs another pair of eyes on it, so that is what I would like to release next. I think there are number of works to draw inspiration from for building a better ecosystem in Rust. For PBA related work, Taichi, Simit and Ebb come to mind.

I currently have a pipeline with a Houdini plugin for gut that allows me to feed Houdini meshes into the simulator and visualize the results in real time. I have merging and splitting because it allows me to feed a bunch of meshes in, that I can split into different connected components before running the simulator and merge on the output for visualization.

I would love to see what you guys have been working on. Probably this thread is not the best place to continue the discussion on, but I'm not too familiar with the current state of affairs when it comes to PBA or scientific computing in the rust community, is there a working group or forum that I can join where we can share and get feedback?

**Comment by Andlon** [comment]
> Yes we are working on something, and I also want to release the code for reproducibility. I am very interested in collaborating on a better ecosystem.
> 
> I have been looking for a solid linear algebra library with lazy linear algebra (like in Eigen) block matrix and sparse matrix capabilities and reasonable performance, but couldn't find anything in Rust (or anywhere else for that matter). A somewhat complete solution for this would include something like sprs, ndarray and nalgebra, but it is not possible to compose these AFAICT. For example, creating a sparse block matrix and then be able to multiply it by a sparse or dense vector or block vector would be nice. I have somewhat of a solution for this I use in my own code, but it has a few warts and definitely needs another pair of eyes on it, so that is what I would like to release next. I think there are number of works to draw inspiration from for building a better ecosystem in Rust. For PBA related work, Taichi, Simit and Ebb come to mind.

It's very interesting that you say this. I have the same requirements. In fact, over the last 2 years I've been working on an experimental prototype that decouples expressions from backends from formats with zero runtime overhead. This means that the formats (Dense, CSR, CSC, literally anything) can be implemented independently from the lazy expression engine, and moreover, the backend used for executing the unary/binary matrix operations can be chosen independently of both format and expressions, provided that the backend implements operations for the given format(s). This means that one can choose the backend to use at a very fine level of granularity: for example, you can choose to run a particular expression with a single-threaded backend, and a multi-threaded (or even GPU/whatever) backend for another expression. This level of granularity is something that is to my knowledge lacking in any other system for lazy evaluation of linear algebra, but I believe this level of control is also necessary, as setting this at a global level is largely insufficient. All this is intended to be user-extensible: backends and formats can be developed by separate crates.

To give you a taste, here's one of the tests for this project (in this case it only checks that it compiles correctly):

```rust
#[test]
fn assign_into_view_composite_expression() {
    let x = DMatrix::<i32>::zero((Dyn(4), Dyn(4)));
    let y = DMatrix::<i32>::zero((Dyn(4), Dyn(4)));
    let mut z = DMatrix::<i32>::zero((Dyn(8), Dyn(8)));
    z.view_mut(2..6, 2..6).assign(3 * &x + 2 * &x + &y * 5);
    z.view_mut(2..6, 2..6).assign(-5 * x + 2 * y);
}
```

Clearly this is a very ambitious project, but the neat thing is that formats and backends can be wrappers on top of existing functionality, so e.g. wrapping different C/C++ libraries would give you full lazily evaluated expression capabilities for free, in addition to a fairly uniform backend/format-agnostic way of accomplishing many common linear algebra tasks.

For the short term, I have a number of pending contributions to `nalgebra` that should vastly improve its support for sparse matrices. Currently this is all integrated in my own code, but I intend to clean it up and separate it into PRs after the SIGGRAPH deadline.



> 
> I currently have a pipeline with a Houdini plugin for gut that allows me to feed Houdini meshes into the simulator and visualize the results in real time. I have merging and splitting because it allows me to feed a bunch of meshes in, that I can split into different connected components before running the simulator and merge on the output for visualization.

That sounds very neat!

> I would love to see what you guys have been working on. Probably this thread is not the best place to continue the discussion on, but I'm not too familiar with the current state of affairs when it comes to PBA or scientific computing in the rust community, is there a working group or forum that I can join where we can share and get feedback?

Indeed, it is not. I am not aware of any collective of PBA researchers working on Rust projects. There's some more interest in scientific computing, but the people seem relatively scattered, and many of the people interested in scientific computing are primarily interested in ML/AI, and they tend to have vastly different requirements. There's some people (including me) hanging out on the `rustsim` Discord server, but it has to be said that the majority of people there appear to be game developers, not researchers.

I suggest that we reconvene after the deadline and discuss this further. You're more than welcome to e-mail me any time (just look at our research group website for contact details).

**Comment by elrnv** [comment]
That looks really exciting! Sounds like our interests are aligned :)
